### ISSUE TITLE
missing veip/pptp information.

### ISSUE THREAD

**Issue by dnfm** [vijays-tikka-masala/was-110-guide#10]
The guide says:

PPTP or VEIP

You need to know if you're on PPTP or VEIP. Check up-n-atom's guide on Discord (link).

But the link at discord gives no information whatsoever on how to check this.

**Comment by vcolmenar** [comment]
This should be the link to the discord message.

https://discord.com/channels/886329492438671420/1173846818535247904

![image](https://github.com/vijays-tikka-masala/was-110-guide/assets/2059746/d8d33051-520e-40b1-8c68-add7264c7aaf)
