### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by stich86** [vijays-tikka-masala/was-110-guide#9]
hi mate,

i've found your Git on my Discord Channel (RTL960x).
Me and other people are working on make a global wiki for all known ONT (xPON) with all useful information (how to access, change paramenters and so on).

Do you want to collaborate with us and integrate information of this XGSPON SFP stick on our wiki?

Let me know. Here the link https://hack-gpon.org/ you can open a PR to add these to our DB

Thanks in advance :)

**Comment by vcolmenar** [comment]
Sure, I'll have a look when I have minute.
Thanks for reaching out!
